name: mongoshop ci

on:
  push:
    branches: 
    - master
    - develop
    
  workflow_dispatch:

jobs:
  build:
    name: Build project on ${{ matrix.os }}
    runs-on: windows-latest
  

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Clean
      run: dotnet clean ./MongoShop/MongoShop.sln --configuration Release && dotnet nuget locals all --clear
    - name: Build
      run: dotnet build --configuration Release
      working-directory: .\MongoShop
      
      
   
