name: mongoshop ci

on:
  push:
    branches: 
    - master
    - develop
    
  workflow_dispatch:

jobs:
  build:
    name: Build project on ubuntu and windows
    runs-on: ${{ matrix.os }}    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
   
