name: mongoshop ci

on:
  push:
    branches: 
    - master
    - develop
    
  workflow_dispatch:

jobs:
  build:
    name: Build project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build
      working-directory: .\MongoShop
      
   
